### ISSUE TITLE
Option to change math separators

### ISSUE THREAD

**Issue by jay-pee** [benwr/ankdown#13]
I can't change my vscode plugin (Markdown All in One) to work with the Math separator syntax which the script is using. In my opinion it should be possible to have a option that ankdown also works with `$` and `$$` by substitute it later in the process to `\( \)` and `\[ \]` with a regular expression.

When I have the time I would do a pull request. Would be nice to get your opinion about it.

Thank you for your work.

**Comment by benwr** [comment]
So, I think in order to get this to work you would need to parse out your custom separators and replace them with `\(`,`\)`, etc., since ankdown has switched to using Anki's builtin mathjax support (which forces you to use those separators). I'd definitely accept a PR that did this is a nice way (one that's extensible to alternate separators and easy to configure).

**Comment by jay-pee** [comment]
Thank you for your fast answer

the question is how to get this extensibility  done.
Something like this maybe:

`ankdown -r [directory] -p [package filename] -s={'$', '$$'} [change math separator to {X, XX}]`

don't know if the syntax is totally right but i hope you get the gist out of it.

**Comment by benwr** [comment]
I think it would be fine if there were a flag for "--dollar-separators"; the main thing is just to make it easy in the code to change them / make them configurable later.

**Comment by benwr** [comment]
Done in #14; thanks @jay-pee!
