### ISSUE TITLE
Can i create deck/card by using visual studio code with markdown plugin?

### ISSUE THREAD

**Issue by Maclaon** [benwr/ankdown#6]
hi，this is great!，can i use [visual studio code](https://code.visualstudio.com/?wt.mc_id=vscom_freedevoffers) with plugin [markdown-preview-enhanced](https://shd101wyy.github.io/markdown-preview-enhanced/#/) to create deck/cards?

**Comment by benwr** [comment]
Yes! I use a similar vscode plugin actually.

**Comment by benwr** [comment]
Just use the syntax described in the help (`%` separates the sides of a note, `---` separates cards), and then point ankdown at your files to generate the package, and import it with anki.

I actually just wrote an anki add-on that automates the importing process, too. It's available at https://github.com/benwr/ankdown-plugin or from the anki add-on web site. Right now it doesn't have any documentation, but I've been using it successfully since last night :P
